application: lfm-genrehistory
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "10m"

handlers:
# Script handlers
- url: /history_data
  script: tag_svc.historyservice.app

- url: /tag_graph_data
  script: tag_svc.taggraphservice.app

- url: /set_shout
  script: setshout.app

- url: /user_fragments
  script: tag_svc.userfragservice.app

- url: /worker
  script: tag_svc.tagworker.app
  login: admin

- url: /admin
  script: admin.app
  login: admin

# Static files mapped below
- url: /history
  mime_type: text/html
  static_files: static/html/history.html
  upload: static/html/history.html
  expiration: "1h"  

- url: /tag_graph
  mime_type: text/html
  static_files: static/html/tag_graph.html
  upload: static/html/tag_graph.html
  expiration: "1h"  

- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  static_files: static/\1
  upload: static/(.*\.(appcache|manifest))
  expiration: "0m"

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/html/\1
  upload: static/(.*\.html)
  expiration: "1h"

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: static/\1
  upload: static/(.*\.ico)
  expiration: "7d"

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.json)
  mime_type: application/json
  static_files: static/\1
  upload: static/(.*\.json)
  expiration: "1h"

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: static/\1
  upload: static/(.*\.xml)
  expiration: "1h"

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# audio files
- url: /(.*\.(mid|midi|mp3|wav))
  static_files: static/\1
  upload: static/(.*\.(mid|midi|mp3|wav))  

# index files
- url: /(.+)/
  static_files: static/\1/index.html
  upload: static/(.+)/index.html
  expiration: "15m"

- url: /(.+)
  static_files: static/\1/index.html
  upload: static/(.+)/index.html
  expiration: "15m"

# site root
- url: /
  static_files: static/html/index.html
  upload: static/html/index.html
  expiration: "15m"


libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6
